version: 2
updates:
  - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Ragin-LundF"
    open-pull-requests-limit: 2
